// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "beijingyingnuoweixun",
            "url": "https://e.gitee.com/beijingyingnuoweixun"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/devices/{id}/channels": {
            "post": {
                "description": "ping 接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "ping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "通道备注",
                        "name": "memo",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "播放类型，pull 媒体服务器拉流，push 摄像头推流,默认push",
                        "name": "streamtype",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "静态拉流地址，streamtype=pull 时生效。",
                        "name": "url",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "1000": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "1001": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "1002": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "1003": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8090",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Video Intelligence",
	Description:      "Video Intelligence",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
